sbncode/CAFAna/StandardRecord/Proxy/parse_xml.py
sbncode/CAFMaker/CAFMaker_module.cc
sbncode/CAFMaker/FillTrue.cxx
sbncode/CAFMaker/FillTrue.h
sbncode/CAFMaker/RecoUtils/RecoUtils.cc
sbncode/CAFMaker/RecoUtils/RecoUtils.h
sbncode/CAFMaker/cafmakerjob_icarus.fcl
sbncode/FlatMaker/gen_flatrecord.py
sbncode/LArRecoProducer/CRTHitMatch_module.cc
sbncode/LArRecoProducer/PMTFlashTriggerMaker_module.cc
ups/product_deps

Title.
Note that there is one caveat to merging this in: sbndcode (through sbndutil) still depends on v01_52_01 of larbatch while uboone/icaruscode depend on v01_53_00. So this update will not build out-of-the-box until that is remedied.

Updates sbncode to LArsoft v09

---

sbncode/NuMuSelection/MuPVertexStudy_module.cc
sbncode/NuMuSelection/NuMuEfficiencyStudy_module.cc
sbncode/NuMuSelection/run_numueff.fcl

A couple leftover things -- see the title.

More changes to the NuMu ana modules that were lost in the previous PR

---

sbncode/CMakeLists.txt
sbncode/TPCReco/CMakeLists.txt
sbncode/TPCReco/TrackSplit/CMakeLists.txt
sbncode/TPCReco/TrackSplit/TrackSplitter_module.cc
sbncode/TPCReco/VertexStub/CMakeLists.txt

A couple leftover things -- see the title.
Depends on https://github.com/SBNSoftware/sbnobj/pull/9.

Tweaks to TPCReco to make it build.

---

sbncode/CAFMaker/FillTrue.cxx

Title -- depends on: https://github.com/SBNSoftware/sbnanaobj/pull/3.

Fix energy filling of truth matching (reverting a previous erroneus commit

---

sbncode/CAFMaker/CAFMaker_module.cc
sbncode/CAFMaker/FillReco.cxx
sbncode/CAFMaker/FillReco.h
sbncode/CAFMaker/FillTrue.cxx
sbncode/LArRecoProducer/RangePAllPID_module.cc

Depends on: https://github.com/SBNSoftware/sbnanaobj/pull/5.

Add in more MCFlux stuff. Add in range-based pion momentum.

---

sbncode/TPCReco/CMakeLists.txt
sbncode/TPCReco/CalorimetryAnalysis/CalorimetryAnalysis_module.cc
sbncode/TPCReco/CalorimetryAnalysis/run_calorimetry_analysis_icarus.fcl

title. 
This update doesn't change anything related to CAF. 
It's an update to a standalone module which has been used by a couple people in SBND/ICARUS to evaluate the calorimetry. There have been some updates in the ICARUS channel mapping which breaks stuff. This pull request remedies those issues.

Get Calorimetry Analysis working in most recent icaruscode.

---

sbncode/CAFMaker/FillReco.cxx
sbncode/CAFMaker/FillReco.h
sbncode/CAFMaker/FillTrue.cxx

Title.
Depends on: https://github.com/SBNSoftware/sbnanaobj/pull/7

Small updates to CAF. Add in direction to SRTrack object.

---

sbncode/CAFMaker/CAFMaker_module.cc
sbncode/CAFMaker/FillTrue.cxx
sbncode/CAFMaker/FillTrue.h

The majority of these come from the simb::GTruth object.

Fill new variables added in sbnanaobj branch feature/gtruth

---

CMakeLists.txt
sbncode/SBNEventWeight/App/CMakeLists.txt

For, at least, gsl_interp2d_bilinear

Weight calculators require GSL

---

sbncode/FlashMatch/FlashPredict_module.cc

Fix error message when metric files are not found.
Addresses #102

Improved FM file error message

---

sbncode/TPCReco/CMakeLists.txt
sbncode/TPCReco/NuVertexChargeTree_module.cc
sbncode/TPCReco/VertexStub/CMakeLists.txt
sbncode/TPCReco/VertexStub/IStubMerge.h
sbncode/TPCReco/VertexStub/PlaneStubMerge_tool.cc
sbncode/TPCReco/VertexStub/PlaneTransform.cxx
sbncode/TPCReco/VertexStub/PlaneTransform.h
sbncode/TPCReco/VertexStub/StubBuilder.cxx
sbncode/TPCReco/VertexStub/StubBuilder.h
sbncode/TPCReco/VertexStub/StubMergeAlgorithms.cxx
sbncode/TPCReco/VertexStub/StubMergeAlgorithms.h
sbncode/TPCReco/VertexStub/TwoPlaneStubMerge_tool.cc
sbncode/TPCReco/VertexStub/VertexChargeVacuum_module.cc
sbncode/TPCReco/VertexStub/VertexStubTracker_module.cc
sbncode/TPCReco/VertexStub/sbn_plane_transform.fcl
sbncode/TPCReco/VertexStub/sbn_stub_merge_tools.fcl
sbncode/TPCReco/run_vertexcharge_sbnd.fcl

A few various updates to stub reconstruction. Doesn't affect anything currently run in production.
Depends on https://github.com/SBNSoftware/sbnobj/pull/13.

Updates to Stub Reconstruction

---

sbncode/PID/sbn_pid.fcl

Update razzle-dazzle to point to weights files on sbnd_data

Update razzle-dazzle Weights

---

sbncode/CAFMaker/CAFMaker_module.cc
sbncode/CAFMaker/FillTrue.cxx
sbncode/CAFMaker/FillTrue.h

Title. Depends on https://github.com/SBNSoftware/sbnanaobj/pull/21 and https://github.com/SBNSoftware/sbncode/pull/141.

Fill Objects for MeVPrtl in StandardRecord

---

sbncode/Calibration/TrackCaloSkimmerSelectStoppingTrack_tool.cc
sbncode/Calibration/fcl/icarus/icarus_trackcalo_skimmer.fcl
sbncode/Calibration/fcl/sbnd/sbnd_trackcalo_skimmer.fcl

Make End Median dQ/dx range configurable. Move range to 2cm in ICARUS.

---

sbncode/CAFMaker/CAFMakerParams.h
sbncode/CAFMaker/CAFMaker_module.cc
sbncode/CAFMaker/CMakeLists.txt
sbncode/CAFMaker/FillTrue.cxx
sbncode/CAFMaker/FillTrue.h
sbncode/CAFMaker/RecoUtils/RecoUtils.cc
sbncode/CAFMaker/RecoUtils/RecoUtils.h

Reverts SBNSoftware/sbncode#183
To merge back SBNSoftware/sbncode#182 after reverting the first merge due to SBNSoftware/sbnanaobj#29 dependency not being ready.

Revert "Revert "Purity and Completeness of PFPs""

---

sbncode/EventGenerator/MeVPrtl/config/numi_kaon_common.fcl

Synchronizes the ICARUS-NuMI location with the neutrino simulation (https://github.com/SBNSoftware/icaruscode/pull/230).

Update ICARUS detector location and detector box

---

sbncode/CAFMaker/FillTrue.cxx

Requires: https://github.com/SBNSoftware/sbnanaobj/pull/36

adding missing geant processes to CAF

---

sbncode/CAFMaker/CAFMakerParams.h
sbncode/CAFMaker/CAFMaker_module.cc
sbncode/CAFMaker/FillExposure.cxx
sbncode/CAFMaker/FillExposure.h

As agreed in the RM meeting this substitutes #225 for the production patch release.

production CAF fix

---

sbncode/EventGenerator/MeVPrtl/Tools/Higgs/HiggsMakeDecay_tool.cc
sbncode/EventGenerator/MeVPrtl/config/Higgs/dissonant_higgs.fcl

Fcl change to the nominal Higgs Portal mixing angle.

Change Nominal Higgs Portal Mixing Angle to 5e-5

---

sbncode/CAFMaker/bin/CMakeLists.txt
sbncode/CAFMaker/bin/file_size_ana

Can make numerical printouts or ring or bar plots of CAF/flatcaf/art file sizes.

Port file_size_ana from NOvA

---

sbncode/Calibration/fcl/icarus/icarus_trackcalo_skimmer.fcl

This change is also desired for the 2021C release branch. So this is a copy of https://github.com/SBNSoftware/sbncode/pull/240 for the release branch of sbncode.

Change RawDigit collection window to 100 ticks on either side.

---

sbncode/CAFMaker/CAFMaker_module.cc

This depends on https://github.com/SBNSoftware/sbnanaobj/pull/60

Fill the new BNB and NuMI size fields

---

sbncode/CosmicID/training_scripts/CRUMBSTMVADriver.C

I have finally been creating some _how to_ resources to go with a technote-style document I am making for CRUMBS. This is an example training script which I feel would be useful to have in sbncode for future retraining.

Add example training script for CRUMBS tool

---

sbncode/CAFMaker/CAFMakerParams.h
sbncode/CAFMaker/CAFMaker_module.cc
sbncode/CAFMaker/FillReco.cxx
sbncode/CAFMaker/FillReco.h

Fills new SROpFlash product into CAFs. See also pull requests in sbnanaobj (https://github.com/SBNSoftware/sbnanaobj/pull/67) and icaruscode (https://github.com/SBNSoftware/icaruscode/pull/409)

Fill SROpFlash into CAFs

---

sbncode/CAFMaker/FillReco.cxx

Marking as draft for now -- I want to make the PRs to do a CI-based test first.

Fill Pfo Characterisation features in CAF files.

---

ups/product_deps

- Include fix in Supera (it just changes the Supera commit hashtag)
- Include fix in `ups/product_deps` for `debug` qualifiers builds

Fix Supera build

---

sbncode/CAFMaker/CAFMaker_module.cc
sbncode/CAFMaker/FillReco.cxx
sbncode/CAFMaker/FillReco.h

Depends on https://github.com/SBNSoftware/sbnanaobj/pull/84.

Fix Calo Point Time and add it PFP T0

---

sbncode/CAFMaker/CAFMaker_module.cc
sbncode/CAFMaker/FillReco.cxx
sbncode/Calibration/TrackCaloSkimmerSelectStoppingTrack_tool.cc
sbncode/Calibration/TrackCaloSkimmer_module.cc
sbncode/EventGenerator/MultiPart/MultiPartRain_module.cc
sbncode/EventGenerator/MultiPart/MultiPartVertex_module.cc
sbncode/FlashMatch/FlashPredict_module.cc
sbncode/GeometryTools/CRTGeoAlg.cc
sbncode/GeometryTools/TPCGeoAlg.cc
sbncode/LArG4/G4InfoReducer_module.cc
sbncode/NuMuSelection/MuPVertexStudy_module.cc
sbncode/NuMuSelection/NuMuEfficiencyStudy_module.cc
sbncode/OpT0Finder/flashmatch/Base/FMWKInterface.cxx
sbncode/PID/Razzle_module.cc
sbncode/SinglePhotonAnalysis/Libraries/Processors.cxx
sbncode/SinglePhotonAnalysis/Libraries/analyze_PandoraReco.cxx
sbncode/SinglePhotonAnalysis/Libraries/fiducial_volume.cxx
sbncode/SinglePhotonAnalysis/Libraries/second_shower_search.cxx
sbncode/SinglePhotonAnalysis/SEAview/SEAviewer.cxx
sbncode/TPCReco/CalorimetryAnalysis/CalorimetryAnalysis_module.cc
sbncode/TPCReco/NuVertexChargeTree_module.cc
sbncode/TPCReco/TrackHit/TrackAreaHit_module.cc
sbncode/TPCReco/VertexStub/StubMergeAlgorithms.cxx

Pursuant to LArSoft/larcorealg#34.

Accommodate breaking changes in geometry

---

sbncode/EventGenerator/MeVPrtl/config/Higgs/dissonant_higgs.fcl

Change ReferenceRayDistance from 104 m to 800 m.

fix ReferenceRayDistance parameter in Higgs Portal generator

---

sbncode/Calibration/CMakeLists.txt
sbncode/LArRecoProducer/CMakeLists.txt
sbncode/SinglePhotonAnalysis/HelperFunctions/CMakeLists.txt

These files were changed to explicitly include libraries needed to build sbncode.

add explicit library includes to some CMakeLists.txt files

---

sbncode/Calibration/TrackCaloSkimmer_module.cc

Small bugfix. I'm confident in this PR and do not need a reviewer.

Bugfix to Calibration NTupler.

---

sbncode/OpT0Finder/flashmatch/Base/BaseFlashHypothesis.h
sbncode/OpT0Finder/flashmatch/Base/FlashMatchManager.cxx
sbncode/OpT0Finder/flashmatch/Base/FlashMatchManager.h

Accompanying PR to https://github.com/LArSoft/larsim/pull/111

Update the namespace of the SemiAnalyticalModel

---

sbncode/TPCReco/VertexStub/StubBuilder.cxx
sbncode/TPCReco/VertexStub/VertexChargeVacuum_module.cc

Feature/gp stub norm fix 

---

sbncode/BeamSpillInfoRetriever/EXTRetriever/EXTRetriever_module.cc
sbncode/CAFMaker/CAFMaker_module.cc
sbncode/EventGenerator/MeVPrtl/MeVPrtlGen_module.cc
sbncode/EventGenerator/MultiPart/MultiPartRain_module.cc
sbncode/EventGenerator/MultiPart/MultiPartVertex_module.cc
sbncode/FluxReader/classes.h
sbncode/OpT0Finder/flashmatch/Base/BaseFlashHypothesis.h
sbncode/OpT0Finder/flashmatch/Base/FlashMatchManager.h
sbncode/PID/Dazzle_module.cc
sbncode/PID/Razzle_module.cc
sbncode/SBNEventWeight/App/SBNEventWeight_module.cc
sbncode/SBNEventWeight/App/SystToolsEventWeight_module.cc
sbncode/SBNEventWeight/Base/WeightManager.h
sbncode/SBNEventWeight/Calculators/CrossSections/GenieWeightCalc.cxx
sbncode/TPCReco/TrackHit/TrackHitDumper_module.cc

Changes for art 3.12

---

sbncode/CAFMaker/CAFMakerParams.h
sbncode/CAFMaker/CAFMaker_module.cc
sbncode/CAFMaker/FillReco.cxx
sbncode/CAFMaker/FillReco.h

This is a duplicate of PR #353 for production release

Add CRTPMT Matching variables to CAFs (production)

---

sbncode/CAFMaker/CAFMakerParams.h
sbncode/CAFMaker/CAFMaker_module.cc
sbncode/CAFMaker/FillReco.cxx
sbncode/CAFMaker/FillReco.h

This is a duplicate of PR #358 for production.

Fix CRT time references in CAFs for data and MC (production)

---

sbncode/CAFMaker/CAFMaker_module.cc

This branch fills the new data members of standard record header introduced by SBNSoftware/sbnanaobj#98.
The catch is that the module does not really know the position of the event in the input file, so it has to keep a local count, which will be skewed if a filter upstream is not feeding all the events of the file. Tough luck.
Matter of discussion and review!!
PR for ICARUS production branch coming after discussion.

CAFMaker fills the source information

---

sbncode/CAFMaker/CAFMaker_module.cc

React to the interface change of SBNSoftware/sbnanaobj#106
Aldo this commit should NOT end in the development branch (**revert** it there).

Remove the constant from SRHeader object [2/2] [SBN2023A]

---

sbncode/TPCReco/VertexStub/config/sbn_stub_merge_tools.fcl

I can self review this PR -- it is a small change and I am satisfied with it.

Disable cross-plane stub merging.

---

sbncode/Calibration/TrackCaloSkimmer_module.cc

Supports the MCS study. Depends on https://github.com/SBNSoftware/sbnobj/pull/94.

Add true trajectory points to truth information for Calibration N-tupler

---

sbncode/FlashMatch/FlashPredict.hh
sbncode/FlashMatch/FlashPredict_module.cc

Added check for empty OpHit array
Added Verbose fhicl parameter

Patch for SimpleFlash

---

sbncode/CAFMaker/FillReco.cxx

Depends on https://github.com/SBNSoftware/sbnanaobj/pull/120.

Add scatter angles in MCS to StandardRecord

---

sbncode/LArRecoProducer/LArReco/TrajectoryMCSFitter.cxx

fix that addresses [comment](https://github.com/SBNSoftware/sbncode/pull/384/files#r1589798179)

last valid point for last segment validity

---

sbncode/EventGenerator/MeVPrtl/Tools/Higgs/HiggsMakeDecay_tool.cc
sbncode/EventGenerator/MeVPrtl/Tools/Higgs/Kaon2HiggsFlux_tool.cc
sbncode/EventGenerator/MeVPrtl/config/Higgs/dissonant_higgs.fcl
sbncode/EventGenerator/MeVPrtl/config/numi_kaon_common.fcl

Backport to the 2023A NuMI release.

Update NuMI flux file location for MeVPrtl. Update a couple HPS configs.

---

sbncode/Calibration/fcl/icarus/icarus_trackcalo_skimmer.fcl
sbncode/Calibration/fcl/sbnd/sbnd_trackcalo_skimmer.fcl
sbncode/TPCReco/TrackSplit/run_tracksplit_icarus.fcl

Add in some parameters missing from the gnocchi fcl block

Add default params to gnocchi

---

sbncode/Calibration/fcl/sbnd/sbnd_trackcalo_skimmer.fcl

Please provide a detailed description of the changes this pull request introduces. If available, also link to a docdb link where the issue/change have been presented on/discussed.

Change the default channel simulation to 2d

---

CMakeLists.txt
ups/product_deps

Reverts SBNSoftware/sbncode#474

Revert "Main"

---

sbncode/DetSim/FilterSimEnergyDeposits_module.cc
ups/product_deps

This PR updates one of the modules to use the updated LArSoft geometry interface.

Fix sim energy module to use updated geometry interface

---

sbncode/BeamSpillInfoRetriever/BNBEXTRetriever/BNBEXTRetriever_module.cc

Please provide a detailed description of the changes this pull request introduces. If available, also link to a docdb link where the issue/change have been presented on/discussed.

Bug Fix: OffBeam ICARUS Accounting, Missed an &

---

sbncode/BeamSpillInfoRetriever/job/run_sbndbnbinfo_sbn.fcl

Hot-fix for SBND pot fcls. Needed sbndbnbinfo->bnbinfo in a few more places.

sbnd POT develop hot fix

---

sbncode/Calibration/CMakeLists.txt
sbncode/Calibration/TrackCaloSkimmerSelectClearCosmicMuon_tool.cc
sbncode/EventGenerator/CMakeLists.txt
sbncode/EventGenerator/WireModGen/CMakeLists.txt
sbncode/EventGenerator/WireModGen/CORSIKAGenSBN.cc
sbncode/EventGenerator/WireModGen/CORSIKAGenSBN.h
sbncode/EventGenerator/WireModGen/FilterPrimarySimChannel_module.cc
sbncode/EventGenerator/WireModGen/FilterPrimarySimEnergyDepo_module.cc
sbncode/EventGenerator/WireModGen/WireModMuon_module.cc
sbncode/EventGenerator/WireModGen/filter_wiremod_sbn.fcl
sbncode/EventGenerator/WireModGen/wiremodmuon_sbn.fcl

Copy of https://github.com/SBNSoftware/sbncode/pull/574, for develop.

WireMod Generator for SBN Develop
