SBNSoftware/sbncode

sbncode/CAFAna/StandardRecord/Proxy/CMakeLists.txt
Restore the status quo from before the sbncaf_srproxy branch overwrote it. No interesting CAFAna macros will run without the SRProxy generated files installed.
=> Restore the status quo from before the sbncaf_srproxy branch

sbncode/CAFMaker/FillTrue.cxx, sbncode/StandardRecord/SRSlice.h, sbncode/StandardRecord/SRTrueInteraction.cxx, sbncode/StandardRecord/SRTrueInteraction.h, sbncode/StandardRecord/SRTruthMatch.cxx, sbncode/StandardRecord/SRTruthMatch.h, sbncode/StandardRecord/classes_def.xml
This PR attempts to remove some of the duplication and confusion around the truth matching in the CAFs. Key change are:
- Remove `eff` and `pur` from true interactions, these belong to the matching object. 
- Removal of duplicated `visE` from the truth match, these belong to the true interaction
- Removed `TruthMatch` which was a redundant copy of `SRTruthMatch`
=> Tidied duplications in slice truth matching

sbncode/CAFMaker/FillTrue.cxx
Depends on update to sbnanaobj: https://github.com/SBNSoftware/sbnanaobj/pull/2.
=> Match more G4 processes. Include an explicit unknown process.

CMakeLists.txt
I could not make CMake happy without adding `${ART_DIR}/Modules` to its include path (`ArtMake.cmake`).
Also I needed to tell CMake to find some more UPS packages.
It is not clear to me if the presence or order of other repositories can make the build work without this modification.
=> Missing inclusions in CMakeLists.txt

sbncode/SBNEventWeight/App/SBNEventWeight_module.cc
so that it's soon enough for downstream modules (CAFMaker) to use it.
Turns out that we had eventweight+cafmaker working, but only in separate jobs. If you run them in a single job, which is the plan, then you run into this need for time travel.
=> Fill the ParameterSet info in beginRun()

sbncode/FlashMatch/FlashPredict_module.cc
I missed updating a variable, thus the global X coordinate of the flash wasn't correct.
The bug itself only affects ICARUS, and not SBND.
=> Fix flashX unfolding bug

fcl/gen/genie/prodgenie_bnb_nu_cosmic_sbn_icarus.fcl, fcl/gen/genie/prodgenie_bnb_nu_cosmic_sbn_sbnd.fcl, fcl/gen/genie/prodgenie_bnb_nu_cosmic_sbn_uboone.fcl, fcl/gen/genie/prodgenie_bnb_nu_sbn_icarus.fcl, fcl/gen/genie/prodgenie_bnb_nu_sbn_sbnd.fcl, fcl/gen/genie/prodgenie_bnb_nu_sbn_uboone.fcl
While looking for something else, I stumbled upon some fcl files that still have GENIE v2 flags. They are still valid, but they should not be used as before.  
They are endemic and should be removed if found in general purpose fcl files. I had a look in the fcl file chain and these were the only one I found.
=> Remove GENIE v2 flag

sbncode/FluxReader/FluxReader.h
Removes unused private field `fNuPdgCode` to fix `c9` compile failure.
=> FluxReader

sbncode/TPCReco/VertexStub/StubBuilder.cxx
[Pandora assigns a wrong value to an unmatched hit](https://github.com/LArSoft/larpandora/blob/ce599557983592f6b6cf359960aa816304b8299a/larpandora/LArPandoraEventBuilding/LArPandoraTrackCreation_module.cc#L265):
```cpp
const int index((hitIndex < hitsFromSpacePoints.size()) ? hitIndex : std::numeric_limits<int>::max());
recob::TrackHitMeta metadata(index, -std::numeric_limits<double>::max());
```
In short, that `std::numeric_limits<int>::max()` should have been `std::numeric_limits<unsigned int>::max()` (and that `index` an `unsigned int` too), but that's not what happened. Data has the wrong value in it, code is relying on that, and we have to work around it.
I am blaming Pandora, but I am not sure that is the only track maker making that mistake.
My proposed workaround is to let …
=> Removed flawed check on hit index

sbncode/CAFMaker/CAFMaker_module.cc
=> Avoid crashing when there are no valid weights if StrictMode=false

sbncode/CAFMaker/FillTrue.cxx, sbncode/CAFMaker/FillTrue.h, sbncode/Calibration/CMakeLists.txt, sbncode/Calibration/TrackCaloSkimmer.h, sbncode/Calibration/TrackCaloSkimmerSelectStoppingTrack_tool.cc, sbncode/Calibration/TrackCaloSkimmer_module.cc, sbncode/Calibration/fcl/icarus_trackcalo_skimmer.fcl
Depends on updates to the sbnobj repository: https://github.com/SBNSoftware/sbnobj/pull/22.
This adds in truth information and end-point-hit saving to the track calorimetry skimmer.
This PR has some urgency -- I would like it to be merged in for this week's release if possible so it can be included in a data processing campaign in ICARUS. 
I would ask @mrmooney to be the reviewer if he is available so that it can be reviewed promptly.
=> Updates to Track Skimming. Add in end-point-hit information and truth information

sbncode/FlashMatch/CMakeLists.txt, sbncode/FlashMatch/FlashPredict.hh, sbncode/FlashMatch/FlashPredict_module.cc, sbncode/FlashMatch/template_generators/generate_simple_weighted_template.py
Substantial improvements to discern in-time and out-of-time interactions.
Particularly, interactions occurring on the far half side of the TPCs will be much better matched. Also now _near time_ interactions, eg cosmics that may be synchronous to the beam, will be time-tagged and match.
- Multi-flash matching, allowing many to many matching. At a minimal cost of processing time.
- Completely decoupled the charge and flash computations.
- New fcl parameters to fine tune the module to improve performance, or to aid with commissioning tasks.
- In particular more control to filter small depositions of charge and light
- Enforce flash and charge concurrence
- Metrics are now created with non split slices
- Substantial improvements in the reconstruction of the flash centre: (flash_x, flash_y, …
=> Simple-Flash Match: multi-matcher, unbiased, tuneable, fast.

sbncode/FlashMatch/FlashPredict.hh, sbncode/FlashMatch/FlashPredict_module.cc
Now my module creates associations for every slice, and not just the ones that are potential neutrino candidates.
There will be warnings related to the size of the assns vector, as now there will be more assns than before. The size should be the same as the `recob::Slice` vector.
=> Improve bookeeping of not-candidate slices

sbncode/CAFMaker/cafmakerjob_sbnd_fmatch.fcl
The `cafmakerjob_sbnd_fmatch.fcl` was missing the definition of `fmatch`. I suspect this was on `cafmakerjob_sbnd.fcl` but got cleaned away, as it shouldn't have been there since `sbndcode` does run `fmatch` by default.
No changes needed for the `cafmaker_icarus` side of things.
=> Add missing definition for fmatch

ups/product_deps
This is a request to move experiment genie_xsec dependency to sbncode.
Open issue details:
https://github.com/SBNSoftware/sbncode/issues/15#issuecomment-889241974
Closes #15 
ExperimentPRs:
https://github.com/SBNSoftware/sbndcode/pull/131
https://github.com/SBNSoftware/icaruscode/pull/222
=> move experiment genie_xsec dependency to sbncode

sbncode/CAFMaker/CAFMaker_module.cc
Title. Needed for the upcoming MCP.
=> Don't crash if weights are not present and strictmode==false

fcl/caf/sbnd/cafmakerjob_sbnd.fcl, fcl/caf/sbnd/cafmakerjob_sbnd_sce.fcl, sbncode/CAFMaker/FillTrue.cxx, sbncode/PID/Dazzle_module.cc, sbncode/PID/Razzle_module.cc, sbncode/PID/sbn_pid.fcl
Updated things to call the correct SimChannel label to match the LArG4 migration.
=> Fixing SBND CAF maker fcl 

sbncode/BeamSpillInfoRetriever/BNBRetriever/BNBRetriever_module.cc, sbncode/BeamSpillInfoRetriever/BNBRetriever/MWRData.cpp, sbncode/BeamSpillInfoRetriever/BNBRetriever/MWRData.h, sbncode/BeamSpillInfoRetriever/EXTRetriever/EXTRetriever_module.cc
This is a proposal to split `sbn::BNBRetriever:;produce()` module method into four functional parts.
The functionality is expected not to have changed.
The `produce()` method has been split into three parts, for trigger information retrieval, spill time discovery and multiwire chamber information matching in time. The latter is also split into the matching itself and the creation of a new record with the matched information.
As side effects a couple of auxiliary data structures have been introduced: a `TriggerInfo_t` carrying around trigger information (which may be in the future replaced by the trigger data product itself) and `MWRdata_t` structure holding information from the database.
I decided not to add class data members to the module, not to make it harder to support _art_ …
=> Splitting BNBRetriever into functional parts

sbncode/BeamSpillInfoRetriever/BNBRetriever/BNBRetriever_module.cc
Adding in a quick hot-fix for when the spills aren't matched to any MWR signals, long term this should be looked into but this gets production going. Marking this as a bug fix.
=> This is a fix for a seg-fault arising from missing MWR devices

sbncode/SBNEventWeight/jobs/genie/eventweight_genie_sbn.fcl
For current genie weight calculators: it takes 1.5 minute to prepare 50 knob for each universe. This effect is linear such that we can speed up the code by using less universes; say 20, then we only need 30 mins to prepare knobs.
=> change genieweight fhicl, universes 100->20

sbncode/BeamSpillInfoRetriever/BNBRetriever/BNBRetriever_module.cc
The issue is that the buffer where `sbn::BNBSpillInfo` entries are kept is never emptied.
~The fix I propose is not fully C++-compliant, since after move a `std::vector` is only guaranteed to be destructible, while we keep reusing it assuming it empty. Adding a `fOutbeamInfos = {};` would make it compliant, but it's just too ugly for me to bear (science!).~ _Edit: checking back the C++17 standard and the common Internet lore, it appears that additional guarantees are provided for STL containers after the move and that the change is actually compliant._
**Important**: this is GitHub coding: I haven't even tried to compile it. C.I. test is imperative here.
**Note**: this pull request is to `develop`; it needs to be merged into the proper 2021C production branch too.
=> BNBRetriever fix: don't write entries incrementally

sbncode/CAFMaker/CAFMaker_module.cc
This fixes the "multiple globalTrees in output" problem for job configurations that don't include any reweights. I think that problem is harmless, but aesthetically unappealing, so if this simple fix could sneak in somewhere that would be good.
=> Add another globalTree bail out condition for the case where the list of labels is empty

sbncode/BeamSpillInfoRetriever/BNBRetriever/BNBRetriever_module.cc
The `event` field of `sbn::BNBSpillInfo` is currently not filled.
This change is supposed to fill it with the _art_ event number.
**Important**: this is another instance of GitHub programming. C.I. test is needed to see if this even _compiles_.
**Note**: this pull request is against `develop`. The commit may need to be added also to the SBN 2021C production branch.
=> BNBRetriever fix: fill event number

sbncode/CAFMaker/CAFMakerParams.h, sbncode/CAFMaker/CAFMaker_module.cc, sbncode/CAFMaker/FillExposure.cxx, sbncode/CAFMaker/FillExposure.h
Adding POT Accounting to CAFs usign output of BNBRetriever module. Fills in SRHeader with one entry per event. More ideal is an entry per subrun.
=> POT Accounting in CAFs using BNB Retriever module

sbncode/OpT0Finder/flashmatch/Algorithms/CMakeLists.txt, sbncode/OpT0Finder/flashmatch/Algorithms/LightPath.h, sbncode/OpT0Finder/flashmatch/Algorithms/PhotonLibHypothesis.cxx, sbncode/OpT0Finder/flashmatch/Algorithms/PhotonLibHypothesis.h, sbncode/OpT0Finder/flashmatch/Base/BaseFlashHypothesis.h, sbncode/OpT0Finder/flashmatch/Base/CMakeLists.txt, sbncode/OpT0Finder/flashmatch/Base/FMWKInterface.cxx, sbncode/OpT0Finder/flashmatch/Base/FMWKInterface.h, sbncode/OpT0Finder/flashmatch/Base/FlashMatchManager.cxx, sbncode/OpT0Finder/flashmatch/Base/FlashMatchManager.h, sbncode/OpT0Finder/flashmatch/CMakeLists.txt
This PS switches from using the `OpFastScintillation` class in `LegacyLArG4` to using the new `SemiAnalyticalModel` class. The `SemiAnalyticalModel` class, introduced with PR LArSoft/larsim#84, returns visibilities instead of number of photons, and the code has been adjusted accordingly. This allows addressing SBND issue SBNSoftware/sbndcode#163.
While working on this, I noticed that the `GeoAlgo` library used by this flash matching and located at `sbncode/OpT0Finder/flashmatch/GeoAlgo` duplicates the library in `larcorealg/GeoAlgo`. This was causing problems when running the `OpT0Finder` module with other modules that use `GeoAlgo` in `larcorealg`. We should change the namespace of the one in `sbncode/OpT0Finder/flashmatch`, but for now I am simply switching to the `larcorealg` one.
=> OpT0Finder with new LArG4

sbncode/OpT0Finder/flashmatch/Algorithms/CMakeLists.txt, sbncode/OpT0Finder/flashmatch/Algorithms/LightPath.h, sbncode/OpT0Finder/flashmatch/Algorithms/PhotonLibHypothesis.cxx, sbncode/OpT0Finder/flashmatch/Algorithms/PhotonLibHypothesis.h, sbncode/OpT0Finder/flashmatch/Base/BaseFlashHypothesis.h, sbncode/OpT0Finder/flashmatch/Base/CMakeLists.txt, sbncode/OpT0Finder/flashmatch/Base/FMWKInterface.cxx, sbncode/OpT0Finder/flashmatch/Base/FMWKInterface.h, sbncode/OpT0Finder/flashmatch/Base/FlashMatchManager.cxx, sbncode/OpT0Finder/flashmatch/Base/FlashMatchManager.h, sbncode/OpT0Finder/flashmatch/CMakeLists.txt
This PR contains the light simulation and reconstruction updates for the SBN2022A release, cherry-picking the required commits to allow compatibility with the SBN2021C branch. Commits taken from:
* https://github.com/SBNSoftware/sbncode/pull/227 (OpT0Finder)
Requires https://github.com/SBNSoftware/sbndcode/pull/253 and https://github.com/LArSoft/larsim/pull/84.
=> Light sim+reco updates for SBN2022A release

sbncode/CAFMaker/CAFMakerParams.h, sbncode/CAFMaker/CAFMaker_module.cc, sbncode/CAFMaker/FillReco.cxx, sbncode/CAFMaker/FillReco.h
CRTHit has two types of timing information. `T0` is a absolute timestamp of a signal, which must be subtracted by the beam gate start timestemp. The other is `T1` which is a relative time w.r.t. beam early warning, but as shown in [SBN-doc-25395, page5](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=25395), `T1` is not yet understood well enough, while we have seen good results from `T0`. 
The default of `CRTUseTS0` atom is changed to `true`, and some lines added to read and subtract trigger/beam_gate timings using `raw::ExternalTrigger` and `raw::Trigger`. There are many conversions between `long long`, `uint64_t`, `double` and `float`, which might not be optimal but at least I checked they works as expected; any comments related to this are welcomed! For MC, we saw the `T0` …
=> Saving CRT T0 instead of T1 in CAF

sbncode/CAFMaker/CAFMakerParams.h
The user is more likely to regret a missing flatcaf than they are to miss the disk space. This is still easy configurable in the job fcl.
https://github.com/SBNSoftware/sbncode/pull/256 is the same thing in develop
=> Default CreateFlatCAF to true

sbncode/LArRecoProducer/LArReco/TrajectoryMCSFitter.cxx, sbncode/LArRecoProducer/LArReco/TrajectoryMCSFitter.h, sbncode/LArRecoProducer/MCSFitAllPID_module.cc
The TrajectoryMCSFitter algorithm has an identical name to one that resides in [larreco](https://github.com/LArSoft/larreco/blob/develop/larreco/RecoAlg/TrajectoryMCSFitter.h). This leads to undefined behaviour which showed up in the CI when testing (unrelated) SBNSoftware/sbndcode#278. By changing the namespace in which our version of the alg resides we can fix this issue.
Kyle from SciSoft has confirmed that my understanding of this is correct and the solution has been tested with the CI system.
=> Fix use of same name algorithm

sbncode/CAFMaker/CAFMaker_module.cc, sbncode/CAFMaker/RecoUtils/RecoUtils.h, sbncode/Calibration/TrackCaloSkimmer.h, sbncode/Calibration/TrackCaloSkimmerSelectStoppingTrack_tool.cc, sbncode/EventGenerator/MultiPart/MultiPartRain_module.cc, sbncode/EventGenerator/MultiPart/MultiPartVertex_module.cc, sbncode/FluxReader/FluxGeoFilter_module.cc, sbncode/FluxReader/FluxReader.cxx, sbncode/GeometryTools/CRTGeoAlg.h, sbncode/GeometryTools/TPCGeoAlg.h, sbncode/NuMuSelection/MuPVertexStudy_module.cc, sbncode/NuMuSelection/MuonS2NStudy_module.cc, sbncode/NuMuSelection/NuMuEfficiencyStudy_module.cc, sbncode/PID/Razzle_module.cc, sbncode/TPCReco/CalorimetryAnalysis/CalorimetryAnalysis_module.cc, sbncode/TPCReco/NuVertexChargeTree_module.cc, sbncode/TPCReco/TrackHit/TrackAreaHit_module.cc, sbncode/TPCReco/TrackSplit/MergedTrackIdentifier_module.cc, sbncode/TPCReco/TrackSplit/TrackSplitter_module.cc, sbncode/TPCReco/VertexStub/VertexChargeVacuum_module.cc, sbncode/TPCReco/VertexStub/VertexStubTracker_module.cc
We expect that larsoft v09_50_00 will be using cetmodules to build the major packages.  Some cleanup was necessary as part of this work.  This means that some headers now need to be included where they are used.  This PR should be fine with the current sbncode release, since it simply adds headers.
=> add headers needed by larsoft v09_50_00

sbncode/BeamSpillInfoRetriever/BNBRetriever/BNBRetriever_module.cc, sbncode/BeamSpillInfoRetriever/NuMIRetriever/NuMIRetriever_module.cc
Emergency PR in order to restart POT accounting efforts after updates to trigger decoding.
When doing the updates to the trigger fragment structure we missed the need to update what is referenced in the POT accounting codes. The fragments pulled for the POT accounting are now updated to match the new trigger system. Only will work with new data with new trigger system (>run 8354). Will need to expand this to create a separate path (via fcl or run number flags) to handle the data with the old trigger fragment. This is easier to handle as we don't need a sophisticated decoder for this so it might just have a pre-run 8354 and post-run 8354. Will need to examine this.
Tested with run 8413 which Maya was reporting issues processing before and both BNB and NuMI are now working and run 8353 …
=> Updates to POT accounting codes to account for new trigger fragment

sbncode/CAFMaker/FillReco.cxx
Same as https://github.com/SBNSoftware/sbncode/pull/271, but based on `develop`.
=> use ts0() instead od ts0_ns in CAFMaker

sbncode/CAFMaker/FillTrue.cxx, sbncode/EventGenerator/MeVPrtl/MeVPrtlGen_module.cc, sbncode/EventGenerator/MeVPrtl/Tools/HNL/Kaon2HNLFlux_tool.cc, sbncode/EventGenerator/MeVPrtl/Tools/Higgs/Kaon2HiggsFlux_tool.cc, sbncode/EventGenerator/MeVPrtl/Tools/IMeVPrtlFlux.h, sbncode/EventGenerator/MeVPrtl/Tools/MixedWeightRayTraceBox_tool.cc
Fix phi computation in RayTracer. Add in more variables, including equivalent neutrino energy. Depends on https://github.com/SBNSoftware/sbnanaobj/pull/71 and https://github.com/SBNSoftware/sbnobj/pull/60.
=> Updates to MeVPrtl Generator

sbncode/CAFMaker/CAFMaker_module.cc, sbncode/CAFMaker/FillTrigger.cxx, sbncode/CAFMaker/FillTrigger.h
Adding trigger information to CAF files in order to compute the time within the beam gate. Requires changes to create a new place for trigger information in order move the `sbn::ExtraTriggerInfo` into sbncode.
Tested on ICARUS data from raw -> CAF stage and successfully extracted the correct trigger information at each stage.
Depends on equivalent PRs in icaruscode, sbnanaobj, and sbnobj
=> Adding trigger information to CAF files to compute time within beam gate

.gitmodules, README.md, sbncode/CMakeLists.txt, ups/product_deps
This PR is part of an effort from the ICARUS ML group to merge our pipeline back into the official production workflow.
* Add `larcv2` dependency in `ups/product_deps` because Supera needs it
* Add `Supera` as a git submodule to make it available to both ICARUS and SBND. Supera is a LArSoft module (and several LArCV modules) that 1. makes truth labels for ML-based reconstruction purpose and 2. produces a LArCV file (input format of the ML-based reconstruction chain) from LArsoft products.
**What needs to happen before this can be merged:**
1. `mrb gitCheckout` currently does not initialize nor update git submodules. I submitted a separate PR [here](https://github.com/art-framework-suite/mrb/pull/12) to make it initialize submodules by default.
3. I will update this PR with a commit for …
=> Add larcv2 dependency + Supera as a git submodule

sbncode/BeamSpillInfoRetriever/NuMIRetriever/NuMIRetriever_module.cc
Fixes a bug where the BeamFolder cache would not be properly filled with spills between two triggers. The old code was:
```
try{auto cur_vec_temp = bfp->GetNamedVector((t_previous_event)-fTimePad,"E:HP121[]");} catch (WebAPIException &we) {}
try{auto cur_vec_temp_2 = bfp->GetNamedVector((t_current_event)+fTimePad,"E:VP121[]");} catch (WebAPIException &we) {}
try{auto packed_MTGTDS_temp = bfp->GetNamedVector((t_current_event)+fTimePad, "E:MTGTDS[]");} catch(WebAPIException &we) {}
```
The first line of code would invalidate the cache if it did not include the time of the most recent spill. Then the second line of code would fill the cache from the previous event to the current event. The final line of code created the bug: it would sometimes re-set the cache to include spills after the …
=> Fix NuMI Spill accounting

sbncode/CAFMaker/CAFMakerParams.h, sbncode/CAFMaker/CAFMaker_module.cc, sbncode/CAFMaker/FillTrigger.cxx, sbncode/CAFMaker/FillTrigger.h
Change SRTrigger filling code to be more in line with the rest of CAFMaker. Setup code to reference all PMT times to the same t0.
Depends on https://github.com/SBNSoftware/sbnanaobj/pull/85.
=> Reference PMT times and Update SRTrigger

sbncode/CAFMaker/CAFMakerParams.h, sbncode/CAFMaker/CAFMaker_module.cc, sbncode/CAFMaker/FillReco.cxx, sbncode/CAFMaker/FillReco.h
CRT T1 is a time reference to the trigger unlike T0 which is an absolute timestamp. When `CRTUseTS0` is set to false and we are saving `T1` in `CRTHit::time`, it should be shift by `+srtrigger.trigger_within_gate`
=> Shifting CRT T0 and T1 properly in CAFMaker

sbncode/SBNEventWeight/App/CMakeLists.txt
CMakeLists.txt was not updated properly in https://github.com/SBNSoftware/sbncode/pull/310. Leave the `SBNEventWeight` as it was before, and adding SystToolsEventWeight to the cet plugin.
=> CMakeLists.txt fixed for SystToolsEventWeight

sbncode/CAFMaker/CAFMaker_module.cc, sbncode/CAFMaker/FillReco.cxx, sbncode/CAFMaker/FillReco.h
Filling `caf::SROpFlash::firsttime` as the first peaktime of the associated OpHit; copied from [icaruscode/Filters/FilterCRTPMTMatching_module.cc#349](https://github.com/SBNSoftware/icaruscode/blob/eff5062ee5f8c61559b505b000511e9f2e383efa/icaruscode/Filters/FilterCRTPMTMatching_module.cc#L349). The "trigger requirement" (https://github.com/SBNSoftware/icaruscode/blob/develop/icaruscode/Filters/FilterCRTPMTMatching_module.cc#L375) part is not available yet; how do we want this to be implemented to caf?
=> Fill opflash firsttime

sbncode/TPCReco/VertexStub/StubBuilder.cxx, sbncode/TPCReco/VertexStub/VertexChargeVacuum_module.cc
Following PR LArSoft/larreco#54, the normalisation tools are supposed to undergo a "setup" stage, which one of ICARUS tools uses to extract the detector clocks data.
This stage was added in `GnocchiCalorimetry` module but not in two modules from `sbncode`.
Without it, for `NormalizeDriftSQLite` tool:
* `debug` code will complain about a failed assertion (verified)
* `prof` code will likely break with a memory access violation
Note that `NormalizeDrift` tool is not affected because it was not optimised like the SQLite twin was (probably just slipped under the radar because it was not included in the workflow).
I expect this issue to have manifested from `v09_71_00` on (when the tools were changed), but I am not aware of reports of failure with that version.
Recommended reviewers: …
=> Added setup stage where normalization tools are used.

sbncode/CAFMaker/CAFMakerParams.h, sbncode/CAFMaker/CAFMaker_module.cc, sbncode/CAFMaker/FillReco.cxx, sbncode/CAFMaker/FillReco.h
This pull request 
* adds a FillCRTPMTMatch() function to FillReco.cxx(h) files. 
*  This function reads a `sbn::crt::CRTPMTMatching` data product. This pull request is dependent on icaruscode pull request #[594](https://github.com/SBNSoftware/icaruscode/pull/594) which changes the location of a CRTPMTMatching data product introduced in icaruscode v09_75_01 to be SBN common (`icarus::crt::CRTPMTMatching` -> `sbn::crt::CRTPMTMatching`). 
* fills a `vector<caf::SRCRTPMTMatch>` with all of the CRTPMT Matches within the CAFMAker_module.cc
This PR is dependent on 
* icaurscode PR #[594](https://github.com/SBNSoftware/icaruscode/pull/594) 
* sbnobj PR #[86](https://github.com/SBNSoftware/sbnobj/pull/86)
* sbnanaobj PR #[95](https://github.com/SBNSoftware/sbnanaobj/pull/95)
=> Add CRTPMT Matching variables to CAFs

sbncode/FluxReader/FluxReaderAna_module.cc
This fixes a bug in calculating the off-axis angle in FluxReaderAna. Thanks @henrylay97 for spotting this!
=> OAA variable in FluxReaderAna

sbncode/CAFMaker/CAFMaker_module.cc, sbncode/CAFMaker/FillReco.cxx
This PR fixes the CRT time references for both data and MC files. In general, we use the CRT Hit T0 variable for MC and CRT Hit T1 variable for data files. 
`CRT Hit T0: CRT Hit timestamp wrt beamgate timestamp`
`CRT Hit T1: CRT Hit timestamp wrt global trigger timestamp` 
For the CAFs, we can use the same time reference (wrt beamgate) for both data and MC CRT Times by shifting the data CRT Hit timestamp to be wrt the beamgate, this is done [here](https://github.com/SBNSoftware/sbncode/blob/develop/sbncode/CAFMaker/FillReco.cxx#L71), `where trigger_within_gate` is the difference between the global trigger and beam gate timestamps.
This PR: 
* Makes sure to use the value stored in fParams.CRTSimT0Offset() for the time reference for MC files. after adding the trigger emulation,  [these …
=> Fix CRT time references in CAFs for data and MC 

sbncode/CAFMaker/CAFMakerParams.h, sbncode/CAFMaker/CAFMaker_module.cc
Fill new variables in the CAFs which count the offbeam gates.
Depends on https://github.com/SBNSoftware/sbnanaobj/pull/99
Does not depend on Joseph's PR (https://github.com/SBNSoftware/sbncode/pull/362) explicitly, but will only fill the CAF variables for input files made using that code.
Tested on ICARUS run 2 numi and bnb offbeam data.
=> Offbeam gate counting for CAFMaker

sbncode/LArRecoProducer/TrackStoppingChi2Alg.cc
This occurs when the dE/dx information is empty. The solution implements proper handling of conditions where there are two or fewer points.
=> Fix segfault in sbn::TrackStoppingChi2Alg::RunFit()

sbncode/CAFMaker/FillReco.cxx
Occasionally one of the variables pandora calculates to describe slices for the SliceID BDT fails. In this scenario most of the metadata isn't filled and the default value (-1 for SBND) is set for the slice ID score. We can use this as a flag for "bad slices" and we should be treating these as clear cosmics anyway (more accurately _not treating them as neutrino slices_).
This PR ensures we check for that default value before this labelling the slices.
=> Catch Bad Slices

sbncode/CAFMaker/CAFMakerParams.h, sbncode/CAFMaker/CAFMaker_module.cc, sbncode/CAFMaker/FillReco.cxx, sbncode/CAFMaker/FillReco.h
Moving OpT0 variables into the cafs. There are _two_ caf variables created:  `slc.opt0` and `slc.opt0_sec`, where the latter is the "secondary" OpT0 object. 
OpT0Finder (in SBND for one-to-many matching) can output more than one match per slice if the slice is split up between two TPCs (matches are TPC specific) or if there are multiple in-time flashes. The default `slc.opt0` is filled with the OpT0 object with the **highest** OpT0 score (best match), and `slc.opt0_sec` is filled with the OpT0 object with the **second highest** OpT0 score. 
For flash-matching, looking at `slc.opt0` would be sufficient. For Q->L charge-likelihood studies, one would likely want information from both TPCs (so look at both `slc.opt0` and `slc.opt0_sec`). 
Dependent on accompanying PR in sbnanaobj …
=> opt0finder objects in cafmaker

sbncode/CAFMaker/CAFMaker_module.cc, sbncode/CAFMaker/FillReco.cxx, sbncode/CAFMaker/FillReco.h
This is meant to replace [PR #355](https://github.com/SBNSoftware/sbncode/pull/355), which had some CI issues based dependency mismatches and became outdate once the patch v09_72_00_04 came out. Hopefully there will be no such issues here! 
Associated with sbnanaobj [PR #105](https://github.com/SBNSoftware/sbnanaobj/pull/105)
=> Fill slice barycenter in production branch, take 2

sbncode/CAFMaker/FillReco.cxx
This PR fills the Matched CRT Hit X,Y,Z positions in the CAFs (I simply forgot to add the line that actually fills the variable). This is close to a duplicate of PR #378, apart from the fix in that PR to the flashGateTime, as this was already being saved in µs in develop.
=> fill Matched CRT Hit positions into SRCRTPMTMatch in CAFs

sbncode/LArRecoProducer/LArReco/TrajectoryMCSFitter.cxx, sbncode/LArRecoProducer/LArReco/TrajectoryMCSFitter.h, sbncode/LArRecoProducer/mcsproducer.fcl, sbncode/LArRecoProducer/mcsproducer_icarus.fcl
include a configurable option (`excludeRegions`) to exclude certain regions of the TPC in MCS calculation. 
- feature was added in a way that introduces minimal change to the existing code. Algorithm skips any breakpoints in defined bad regions, as it previously did for bad `segradlengths` values.
- excluded regions can be defined as volume boxes, and should be passed in the format of one list. Code will slice up the list in blocks of 6 numbers, and treat each block as values for boundaries of the region to be exluded: [x_low, x_high, y_low, y_high, z_low, z_high]. Code will check that the passed list is a multiple of 6, and if it is not, will log an error and not exclude any regions
- adding a fcl for ICARUS, `mcsproducer_icarus.fcl`, that uses an angular resolution value of 10mrad …
=> exclude region feature

sbncode/CAFMaker/CAFMakerParams.h, sbncode/CAFMaker/CAFMaker_module.cc, sbncode/CAFMaker/FillReco.cxx, sbncode/CAFMaker/FillReco.h
Associated with the following requests in other packages:
icarusalg - https://github.com/SBNSoftware/icarusalg/pull/77
sbnobj - https://github.com/SBNSoftware/sbnobj/pull/101
sbnanaobj - https://github.com/SBNSoftware/sbnanaobj/pull/113
icaruscode - https://github.com/SBNSoftware/icaruscode/pull/646
=> Barycenter flash match for production patch

sbncode/LArG4/G4InfoReducer_module.cc
The change only applies to SEDLite data structure used in ML reco. 
The SEDLite x,y,z positions are centered w. r. t. the SED voxel.
The change is contained within the module. `sbncode/sbncode/LArG4/G4InfoReducer_module.cc`
=> SEDLite position is centered

sbncode/CAFMaker/CAFMakerParams.h, sbncode/CAFMaker/CAFMaker_module.cc, sbncode/CAFMaker/FillReco.cxx, sbncode/CAFMaker/FillReco.h
sbncode updates - Add barycenter flash match objects into CAFmaker and shift the data time variables to beam reference
Associated Pull Requests ---
sbnobj PR- https://github.com/SBNSoftware/sbnobj/pull/99
sbnanaobj PR- https://github.com/SBNSoftware/sbnanaobj/pull/111
sbncode PR- https://github.com/SBNSoftware/sbncode/pull/392
icaruscode PR- https://github.com/SBNSoftware/icaruscode/pull/641
=> Introduce Barycenter Flash Match

sbncode/CAFMaker/CAFMaker_module.cc
Fill pot and beam information in the CAFs per subrun instead of per file and make sure it is filled in both blind and prescaled files.
=> Fix bug in filling exposure information in CAFs

sbncode/SBNEventWeight/App/SystToolsEventWeight_module.cc
This PR will handle "dependent" dials properly.
For instance, now we can group dependent dials (e.g., FSI knobs) and throw multisim universes. An example output from UniverseOracle looks like below:
```
72: GENIEReWeight_ICARUS_v1_multisim_FSI_pi_VariationResponse, type 0, 100 universes, adjusted parameters:
FrAbs_pi
FrCEx_pi
FrInel_pi
MFP_pi
```
=> Updating SystTool module for Dependent dials

sbncode/CAFMaker/FillReco.cxx, sbncode/CosmicID/CRUMBS_module.cc, sbncode/CosmicID/sbn_crumbs_producer.fcl, sbncode/CosmicID/training_scripts/CRUMBSTMVADriver.C
This PR adds OpT0 variables as an alternative flash matching input to the CRUMBS tool (already makes use of SimpleFlash). This was discussed in various docDBs, the most relevant being [31598](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=31598) and [33367](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=33367).
The default is being set as using OpT0 given the marginally better performance but support is retained for the training of either type. I have also swept some name changes of CRT variables into this PR such that we only need to change the weights once for this round of updates.
Finally, I am making it a draft PR for two reasons:
- ~This PR requires the (approved) CRT Clustering PRs to be merged first, until then the diff will look huge, it's not.~
- The new …
=> OpT0 CRUMBS

sbncode/EventGenerator/MeVPrtl/Tools/BNBKaonGen_tool.cc, sbncode/EventGenerator/MeVPrtl/Tools/HNL/HNLMakeDecay_tool.cc, sbncode/EventGenerator/MeVPrtl/config/bnb_kaon_common.fcl, sbncode/EventGenerator/MeVPrtl/config/bnb_kaon_sbnd.fcl
Re weighted flux files in boone ntuple format to keep up with most  recent SciBooNE measures. I collaborated with Zarko Pavlovic to make the reweigh of the original files. More info can be found in [docdb 31883](
https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=31883).
The code, previous files and re weighted flux files can be found in:
`/cvmfs/sbn.osgstorage.org/pnfs/fnal.gov/usr/sbn/persistent/stash/physics-rodrigoa/`
To make sure reweigh was properly done, validation plots like this one were performed in different kinematic variables, showing a small difference within 5%, which was the expected behavior.
This PR is linked to  [sbncode PR #415](https://github.com/SBNSoftware/sbndcode/pull/415)
=> Updated Flux files for the HNL simulation using the Kaon BNB flux

sbncode/LArG4/CMakeLists.txt, sbncode/LArG4/G4InfoReducer_module.cc, sbncode/LArG4/MergeSimSourcesSBN_module.cc, sbncode/LArG4/SimpleMerge_module.cc, sbncode/LArG4/simplemerge.fcl
Makes simple merge modules which combines `MCParticle` vectors, with the option to set mother IDs. Also adds a simple check to `MergeSimSourcesSBN` which checks that `MCParticle` is also merged if the associations are merged.
Replaces [this PR](https://github.com/SBNSoftware/sbncode/pull/404) so we can combine simple and sbn merge into a single PR.
=> Simple merge and SBN merge changes

sbncode/LArG4/PhysicsLists/SBN_QGSP_BERT_NNC.cc
Validated via de-excitation light spectrum.
=> Moving to HadronHP for low energy hadron simulation.

sbncode/CAFMaker/CAFMaker_module.cc, sbncode/CAFMaker/FillReco.cxx, sbncode/TPCReco/CNNHitClassification/CMakeLists.txt, sbncode/TPCReco/CNNHitClassification/CNNID_module.cc, sbncode/TPCReco/CNNHitClassification/pointidalg_sbnd.fcl, sbncode/TPCReco/CNNHitClassification/run_cnnid_sbnd.fcl, sbncode/TPCReco/CNNHitClassification/sbn_cnnid.fcl
**note**:  this module will only run with `e26` and fail for `c14` due to TensorFlow dependency 
Updates to `CNNID_module`
- fix `PointIdAlg` but where `setWireDriftData` wasn't configured correctly
- include hits associated with parent PFP for `endMichelScore` calculation (considering the case of misclustering)
Updates to fcls
- set NN model file path relative to `FW_SEARCH_PATH`
- default `WireLabel` to WireCell 2D simulation label `simtpc2d:gauss`
- don't apply sparse inference by default
=> updates to CNNID

sbncode/DetSim/AdjustSimForTrigger_module.cc
In the process of reviewing [`icaruscode` #673](https://github.com/SBNSoftware/icaruscode/pull/673), it was discovered that the CRT hits were not being shifted and therefore CRT-PMT matching was broken by this module as the CRT hit times no longer matched the OpFlash times. To rectify this, I have updated the module allowing it to now shift the `sim::AuxDetIDE` according to the emulated trigger time, which can then be used as input to the CRT DetSim. This is accomplished by recreating the collection of `std::vector<sim::AuxDetSimChannel>` and reconstructing each channel with a new `std::vector<std::AuxDetIDE>`, which has `entryT` and `exitT` shifted by the value of the trigger time.
=> Add ability to shift sim::AuxDetIDEs by the trigger time.

sbncode/CAFMaker/FillReco.cxx
Backport to the 2023A NuMI release. Depends on https://github.com/SBNSoftware/sbnanaobj/pull/127.
=> Add scatter angles in MCS to StandardRecord

sbncode/CAFMaker/FillTrue.cxx
For G4 (reweight) study, we save non-primaries to truth.prim.
=> Saving non-primaries in cafs for g4 study [release/SBN2023A_NuMI]

sbncode/LArG4/PhysicsLists/SBN_QGSP_BERT_NNC.cc
This PR restores the `SBN_QGSP_BERT_NNC` physics list to be "`QGSP_BERT` with no neutron cut".
Two separate PRs should follow, one for SBND and one for ICARUS, where the `QGSP_BERT_HP` physics list is adopted:
See issue #453 for more details.
=> Restore SBN_QGSP_BERT_NNC to be QGSP_BERT with no neutron cut

sbncode/CAFMaker/FillReco.cxx
This PR just ensures that CAFMaker continues to pickup the correct variable (for MC) when changes are made in `sbnobj` to the format of the CRT reconstruction objects.
This should be merged together with accompanying PRs in `sbnobj` (SBNSoftware/sbnobj#113) and `sbndcode` for compilation reasons.
=> Keep CAF happy with CRT

sbncode/CAFMaker/CAFMaker_module.cc, sbncode/CAFMaker/FillReco.cxx, sbncode/CAFMaker/FillReco.h
This PR addresses some final comments by @PetrilloAtWork on sbncode PR #482 that reassigns the CRT-PMT flashClassification while filling CAFs using a function.
In this PR I've removed some unused counters in the FillCRTPMTMatch function definition (pointed out in [this comment](https://github.com/SBNSoftware/sbncode/pull/482#pullrequestreview-2455712535) ). 
This PR should be merged alongside sbnobj PR#[116](https://github.com/SBNSoftware/sbnobj/pull/116).
=> CRTPMTMatching fix: remove unused counters 

sbncode/Cluster3D/SnippetHit3DBuilderSBN_tool.cc
A segfault was reported in Cluster3D in larsoft v10 testing. Traced to SnippitHit3DBuilderSBN where it was found that the move to v10 had removed the initialization of the geometry service. Restored this and also modifed the loop over TPCIDs (where the segfault was occuring since taht was the first use of the geometry service) to iterate over TPCGeo. Confirmed that it is running again. 
- [yes] Have you added a label? (bug/enhancement/physics etc.)
- [yes] Have you assigned at least 1 reviewer?
- [apparently not] Is this PR related to an open issue / project?
- [no] Does this PR affect CAF data format? If so, please assign a CAF maintainer as additional reviewer.
- [no] Does this PR require merging another PR in a different repository (such as sbnanobj/sbnobj etc.)? If so, please link it …
=> Fix of segfault in cluster3d

sbncode/CAFMaker/FillTrue.cxx
Depends on https://github.com/SBNSoftware/sbnanaobj/pull/135.
=> Add RadioactiveDecayBase to CAFMaker

sbncode/Calibration/TrackCaloSkimmer_module.cc
It is sometimes useful to exclude hits with poor fits when doing analysis with the calibration ntuples. This PR fills a new field in the `sbn::HitInfo` object with `recob::Hit::GoodnessOfFit` score so that it is available in the calibration ntuples.
Required sbnobj PR: https://github.com/SBNSoftware/sbnobj/pull/122
=> Add hit goodness to sbn::HitInfo

sbncode/Calibration/TrackCaloSkimmer.h, sbncode/Calibration/TrackCaloSkimmer_module.cc, sbncode/Calibration/fcl/icarus/icarus_trackcalo_skimmer.fcl, sbncode/Calibration/fcl/sbnd/sbnd_trackcalo_skimmer.fcl
Refactor each T0 into its own field. 
Depends on: https://github.com/SBNSoftware/sbnobj/pull/124
=> Fix Handling of CRT in Calbiration NTupler

sbncode/CAFMaker/FillReco.cxx
No one in the CRT team has been using CAFs for data work so this hadn't been picked up yet. We should swap the CAFs to use the Ts0 timestamp in both MC & Data. This is because it is the field we reference to the event trigger and has the closest meaning between MC & Data (see especially SBNSoftware/sbndcode#672). This is a last minute patch that should be included in the upcoming production. Apologies for the late notice.
Note, SBND & ICARUS use separate objects & filling of the StandardRecord for our CRT information - this ONLY impacts SBND.
A more detailed study of the CRT in the CAFs would be worthwhile in time for the next production.
=> Use Ts0 not Ts1

sbncode/LArG4/MergeSimSourcesSBN_module.cc, ups/product_deps
This is a required PR following larsim v10_03_00, in larsoft v10_05_00 and later. 
[larsim/#151](https://github.com/LArSoft/larsim/pull/151) introduced a required bool to skip G4 tracks when merging SimChannel objects or not. This PR adds this object + the concomitant "SkipSimChannelTrackIDs" fcl switch (default false).
Calling on @gputnam to review this change.
=> Modify `MergeSimChannels` signature with check to skip G4 tracks or not

sbncode/CAFMaker/CAFMakerParams.h, sbncode/CAFMaker/CAFMaker_module.cc, sbncode/Calibration/TrackCaloSkimmer_module.cc, sbncode/DetSim/AdjustSimForTrigger_module.cc, sbncode/DetSim/FilterSimEnergyDeposits_module.cc, sbncode/DetSim/fcl/icarus_simedepfilter.fcl, sbncode/LArG4/MergeSimSourcesSBN_module.cc
This PR makes updates to sbncode necessary to enable the Spring production in ICARUS. It depends on:
https://github.com/SBNSoftware/sbnobj/pull/124
https://github.com/LArSoft/larsim/pull/151
https://github.com/WireCell/wire-cell-toolkit/pull/400 (will need a new cut of WireCell+LArSoft with this in)
https://github.com/SBNSoftware/sbnobj/pull/129
It incorporates (https://github.com/SBNSoftware/sbncode/pull/525), and can be merged in after that one.
In addition to updating the calbiration NTupler, it includes updates to CAFMaker to support overlays (from @icaromx) and updates to the new MergeSimSources module interface in LArSim (from @jzennamo).
It incorporates https://github.com/SBNSoftware/sbncode/pull/535, and can be merged either instead of or after that PR.
=> Updates to Enable ICARUS Spring Production

sbncode/CAFMaker/CAFMaker_module.cc, sbncode/CAFMaker/FillReco.cxx, sbncode/CAFMaker/FillReco.h
OpFlash information is currently not being saved in CAF files in SBND. This PR splits the `FillOpFlash` function into two detector-specific functions so the OpFlash information can be filled also for SBND. 
Eventually, both functions could be modified to converge into a common function that does the job.
This PR depends on https://github.com/SBNSoftware/sbnanaobj/pull/138
=> Save OpFlash information in CAF files in SBND. 

sbncode/CAFMaker/CAFMakerParams.h, sbncode/CAFMaker/CAFMaker_module.cc, sbncode/CAFMaker/FillReco.cxx, sbncode/CAFMaker/FillReco.h
This Pull request introduces the CRTHit tagging into CAF, so that ICARUS analyzers can use relevant information for out of time rejection.
This PR uses an existing SR and Fill function which have been modified accordingly.
This PR needs a new dependence on this PR for sbnanaobj:
https://github.com/SBNSoftware/sbnanaobj/pull/139
=> This PR introduces CRT Tagging usage into cafs for analyzers

sbncode/HitFinder/ChannelROIToWire_module.cc
Fixes bug in ChannelROI to Wire (back-)conversion introduced in https://github.com/SBNSoftware/sbncode/pull/535.
=> Apply ADCScaleFactor correctly

sbncode/Calibration/TrackCaloSkimmer.h
In develop by mistake the include for CRTT0TaggingInfo and CRTT0TaggingTruthInfo were point to the wrong file: .cc instead of .hh
This PR fixes that.
=> TrackCaloSmikker object: include changed

sbncode/Calibration/TrackCaloSkimmer_module.cc
This PR fixes a bug in how the calib ntuples make use of the CRT track T0 tagging. There was no accounting for the fact that the drift direction is different in the two TPCs so the xshift has to be in different directions depending on which TPC is being considered.
Please see slides linked investigating the issue: https://docs.google.com/presentation/d/1CJ8yL7P7Dae1H3r_99cGIuQ4Dqgc2nATDqnGpyKvbaE/edit?usp=sharing
I haven't presented these slides because a hotfix was requested. I can present them at a future calibration meeting. The key plots are shown below. They show the TPC track start in x for tracks that have been shifted by the CRT T0 values.
**Before Fix**
**After Fix**
=> Ensure CRT T0 usage in calibration ntuples is direction aware

sbncode/CAFMaker/CAFMakerParams.h, sbncode/CAFMaker/CAFMaker_module.cc, sbncode/CAFMaker/CMakeLists.txt, sbncode/CAFMaker/FillReco.cxx, sbncode/CAFMaker/FillReco.h
This pull request reads the special PMT Beam timing signal (RWM) into the CAFMaker which enables us to reconstruct the Beam Bunch structure seen by ICARUS PMTs. 
The PMT Beam signals were originally stored in an icaruscode data product `icarus::timing::PMTBeamSignal`, but [icaruscode PR #832](https://github.com/SBNSoftware/icaruscode/pull/832) and  [sbnobj PR #130 ](https://github.com/SBNSoftware/sbnobj/pull/130) together move the data product to a SBN common area, `sbnobj/Common`. 
A `std::vector<sbn::timing::PMTBeamSignal>` is read into the CAFMaker and then passed to `FillICARUSOpFlash` if the `PMTBeamSignal` is valid. If running on MC, offbeam data or stage1 files without the `sbn::timing::PMTBeamSignal` data product, the `srflash.rwmtime` variable will be left to it's default value …
=> Add PMT Beam Signal timing to ICARUS CAFs 

sbncode/Calibration/CMakeLists.txt, sbncode/Calibration/TrackCaloSkimmerSelectClearCosmicMuon_tool.cc, sbncode/EventGenerator/CMakeLists.txt, sbncode/EventGenerator/WireModGen/CMakeLists.txt, sbncode/EventGenerator/WireModGen/CORSIKAGenSBN.cc, sbncode/EventGenerator/WireModGen/CORSIKAGenSBN.h, sbncode/EventGenerator/WireModGen/FilterPrimarySimChannel_module.cc, sbncode/EventGenerator/WireModGen/FilterPrimarySimEnergyDepo_module.cc, sbncode/EventGenerator/WireModGen/WireModMuon_module.cc, sbncode/EventGenerator/WireModGen/filter_wiremod_sbn.fcl, sbncode/EventGenerator/WireModGen/wiremodmuon_sbn.fcl
This module extends the CORSIKA gen module to filter on muons to get a sample enriched in those that cross either a configured set of CRT planes, or the cathode.
=>  New Event Generator for MC Muons Enriched in T0-taggable Tracks

sbncode/CAFMaker/CAFMakerParams.h, sbncode/CAFMaker/CAFMaker_module.cc, sbncode/CAFMaker/CMakeLists.txt, sbncode/CAFMaker/FillTrigger.cxx, sbncode/CAFMaker/FillTrigger.h
This includes updates to FillTrigger.cxx to take trigger data products from detsim to be able to put them in the cafs: the variables include a bool of passed/failed trigger, number of PMT pairs over threshold, and two variables for the purpose of validation giving us the trigger response in a flattened vector and the size of the pulses (so the vector can be un-flattened).
This pull request must be merged after the [detsim updates](https://github.com/SBNSoftware/sbndcode/pull/830) and with the other updates for the CAF files: [sbnanaobj](https://github.com/SBNSoftware/sbnanaobj/pull/161) and [sbnobj](https://github.com/SBNSoftware/sbnobj/pull/146).
=> Update CAFMaker to fill new trigger variables
